[build]
  # This is the directory to change to before starting a build.
  command = "CI= npm run build"
  base    = "/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "build"

  
